# fly.toml app configuration file generated for elisoccorso-watch on 2026-04-18T21:48:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'elisoccorso-watch'
primary_region = 'cdg'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[processes]
  app = 'python main.py'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
